kind: Deployment
apiVersion: apps/v1
metadata:
  name: devpro
spec:
  replicas: 2
  selector: # tells the controller which pods to watch/belong to
    matchLabels:
      app: devpro
  template:
    metadata:
      labels:
        app: devpro
    spec:
      containers:
        - name: devpro
          image: parthnautiyal/pipeline-demo
          imagePullPolicy: Always
          ports:
            - containerPort: 80
