kind: Service
apiVersion: v1
metadata:
  name: mrdevops
  labels:
    app: mrdevops
spec:
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31000
  selector:
    app: mrdevops
  type: LoadBalancer
