kind: Service
apiVersion: v1
metadata:
  name: devpro
  labels:
    app: devpro
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31200
  selector:
    app: devpro
  type: LoadBalancer
